# Generated by Django 5.0.6 on 2024-05-11 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_file_field_user_float_field_user_image_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_field',
            field=models.TimeField(default=datetime.time(12, 36, 7, 28252)),
        ),
    ]
