# Generated by Django 5.0.6 on 2024-06-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Muisician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muisician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Muisician.muisician')),
            ],
        ),
    ]
